#!/bin/bash
# Outputs to file the same blocks, but adding
# LEFT-WALL at the beginnig of it
# Useful for files generated by DNN without LEFT-WALL

# takes two arguments: file to get blocks from, file to ouput WALL-ed blocks

# usage: add_LEFTWALL.sh file outfile

uniq $1 | awk -v RS='\n\n' '$0="###LEFT-WALL### "$0"\n"' > $2
# uniq removes all duplicated newlines
# awk 	-v RS defines the record separator as an empty line
#		then awk adds ###LEFT-WALL### at the beginning of the block